### ISSUE TITLE
Compile Indicates Multiple Gradle Deprecation Warnings

### ISSUE THREAD

**Issue by DrAnonymous** [sparkled/sparkled#183]
When compiling with:  ./gradlew clean --warning-mode all copyWebUi shadowjar

The following deprecation warnings are listed:

**> Configure project :**
The runtime configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the runtimeOnly configuration instead.
        at build_3bmrtxnte520xxto9sshb4yc6$_run_closure2$_closure10.doCall(/snipped/gitrepos/sparkled/build.gradle:51)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
The baseName property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveBaseName property instead.
        at build_3bmrtxnte520xxto9sshb4yc6$_run_closure4.doCall(/snipped/gitrepos/sparkled/build.gradle:105)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)

Multiple warnings from **> Task : model persistence etc:kaptKotlin**
Annotation processors discovery from compile classpath is deprecated.
Set 'kapt.includeCompileClasspath = false' to disable discovery.

**> Task :shadowJar**
Property 'transformers.$0.serviceEntries' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.

**Comment by chrisparton1991** [comment]
Thanks @DrAnonymous, I have an issue open (#165) to upgrade Gradle, I'll be looking at fixing any Gradle-related warnings as part of that.

I'll leave this issue open as a reminder to address these specific issues.

**Comment by chrisparton1991** [comment]
I've recently started working on Sparkled again after a long break. I've upgraded to Gradle 7 in a new branch and am working on overhauling a bunch of things.
