### ISSUE TITLE
Unable To Start App From Chrome With 0.1.2 Build

### ISSUE THREAD

**Issue by DrAnonymous** [sparkled/sparkled#184]
Performed a fresh compile and started app on OSX. Chrome gives a file not found error when accessing: localhost:8080. The application log shows: 

_2020-12-13 15:36:12,357 [pool-1-thread-7] ERROR io.sparkled.rest.ErrorController - Failed to find index.html._

Full startup log attached.As an aside the jar file produced in build/libs is named: sparkled-0.1.1.jar, even though it was from 0.1.2.

[sparkled.log](https://github.com/sparkled/sparkled/files/5685676/sparkled.log)

**Comment by chrisparton1991** [comment]
I probably haven't pushed up the commit to change the version number yet sorry. Until recently Jenkins CI was taking care of releases, but it will no longer be providing free support to open source repositories. I'll be moving to GitHub Actions next year.

In your previous issue you had a build command of ` ./gradlew clean --warning-mode all copyWebUi shadowjar`.

You'll need to add `buildWebUi` to the command:
```
 ./gradlew clean --warning-mode all buildWebUi copyWebUi shadowjar
```

`buildWebUi` instructs Gradle to run the NPM task that builds the production webapp, then `copyWebUi` simply copies the built webapp into the resources folder prior to the jar file being built.

Note that Sparkled still has a LOT of rough edges :) I'm planning on giving it a lot of attention in 2021 though!

**Comment by DrAnonymous** [comment]
Was about to post a new comment about figuring out some of the issue and your's came up first. :)

Rough edges are fine, since that means there's room to grow.
