### ISSUE TITLE
Unable to connect to server: "AuthorizationException: null"

### ISSUE THREAD

**Issue by bigfoott** [sparkled/sparkled#210]
Hi! I'm having trouble getting the server started. I've attached a log file where I tried connecting twice. The issue starts with:

```
2022-09-18 01:05:44,803 [io-executor-thread-2] ERROR io.sparkled.rest.ErrorController - Unexpected error response for URI '/':
io.micronaut.security.authentication.AuthorizationException: null
```

I get "An unexpected error occurred." when navigating to localhost:8080.

I should also mention that I'm attempting to run this on WSL on Windows 10.

Let me know if there's anything I can try. Hopefully it isn't something obvious that I missed :) Thanks!

[sparkled.log](https://github.com/sparkled/sparkled/files/9593108/sparkled.log)

**Comment by chrisparton1991** [comment]
Hi @bigfoott, is this using one of the release versions, or did you build it yourself? The last release version (0.1.2) on GitHub is pretty old, unfortunately.

If you built it yourself, you need to make sure to build the UI component using the following command:
```
./gradlew clean copyWebUi shadowJar
```

Without the `copyWebUi` task being run, the React web UI won't be built and copied into the final jar file.

That said, there's a lot of stuff (in the frontend particularly) that's far from complete, you're more than welcome to poke around and I'll help you get it up and running, but definitely lots of work still to be done :) 

Unfortunately I've been flat out with work and life, and haven't had much time to devote to the project recently. Cool to see some interest in it though! Here are some lights I had running on it back in 2018: https://www.youtube.com/watch?v=AGep9PSoO48

**Comment by bigfoott** [comment]
Hi! I built it myself. Followed the instructions in the [Installing](https://github.com/sparkled/sparkled#installing) section of the readme. Had to fix a few things like incorrect java version etc, but it finally built after a few tries lol.

I ended up using this command from #184 while trying to figure out why it wouldn't build:
`./gradlew clean --warning-mode all buildWebUi copyWebUi shadowjar`

I realize it's an older issue, but i'm not sure if that command would cause the issue I'm experiencing. I'll try again now that I figured out the java version issue and see if it works this time :)

And awesome video! I found it while poking around when I first found this project a few days ago. I'll be starting with something basic this Christmas, but hope to build upon it over the next few years :)

**Comment by bigfoott** [comment]
Tried building again using the command you provided and I seem to get the same error. I've attached the log for that attempt as well.
[sparkled2.log](https://github.com/sparkled/sparkled/files/9593385/sparkled2.log)

**Comment by chrisparton1991** [comment]
Hmm strange, possibly something broke during some version upgrades I made a little while back. I'll take a look tomorrow and get back to you :) 

I'm hoping to get some work done on Sparkled before Christmas this year, especially to fix up some of the more egregious UI issues that came from a not-quite-finished rewrite.

**Comment by bigfoott** [comment]
Sounds good! No rush if you have other priorities :) We're still a ways away from Christmas, though I am eager to start messing around with this :)

Note about the "sparkled2.log" I provided - Turns out that's the same as the first log file I sent. I ran in to the same issue however, so I assume it's the same issue.

I tried using [this fork](https://github.com/chrisparton1991/sparkled) of yours, as it predates [the version updates from July](https://github.com/chrisparton1991/sparkled/compare/master...sparkled:sparkled:master), but I ran into some other errors, which I assume are also version errors.

[sparkled3.log](https://github.com/sparkled/sparkled/files/9593495/sparkled3.log)

**Comment by chrisparton1991** [comment]
@bigfoott thanks for attaching the logs. I've pushed up a commit that will hopefully fix your issue. There was a typo in one of the webUi gradle tasks, and Micronaut Security was getting in the way of accessing the static web files. I hadn't noticed because during local development I start up my own NPM server to host the web stuff.

Anyway, try the latest Sparkled master and run `./gradlew clean copyWebUi build` and let me know how you go. You might need to delete `sparkled.db` beforehand, as switching branches might have messed up the data migrations.

I added a disclaimer to the top of the README stating that it's pre-alpha 😁 

Let me know how you go!

**Comment by bigfoott** [comment]
It seems to have worked! I had to build with this command, otherwise it said index.html was missing:

```
./gradlew clean --warning-mode all buildWebUi copyWebUi shadowJar
```

I'll start messing with it tomorrow :) Quick question - is it possible to expose the :8080 port to the local network? I have the server running off a separate computer and would like to access it from my main PC. Thanks!

**Comment by chrisparton1991** [comment]
@bigfoott The ESP will remain in "connecting" mode until it receives the first data packet from Sparkled.

Steps to get something displaying:
 - Create a stage with at least one stage prop
 - Update the `STAGE_PROP_CODES` constant in `config.h` to match the stage prop name if need be (by default it's `PROP_1`)
 - Create a Song
 - Create a Sequence using that Song
 - In the sequence editor, add at least one effect (the UI here is a bit crappy and slow, same with the stage editor sorry! I'm aware of it and want to fix it)
 - Publish the sequence
 - On the dashboard page, click the hamburger icon next to the sequence and play it

**Comment by bigfoott** [comment]
@chrisparton1991 Thanks! I believe I did everything above minus the publishing and then playing from the dashboard. However, clicking "Play sequence" from that menu doesn't seem to do anything. No errors in the browser console.

Opened up sparkled.log and found this line:
```
2022-09-19 20:26:56,811 [playback-service-0] ERROR i.s.m.impl.MusicPlayerServiceImpl - Failed to play sequence test: No line matching interface Clip supporting format PCM_SIGNED unknown sample rate, 16 bit, stereo, 4 bytes/frame, big-endian is supported..
```
Is this an issue related to the specific format of the mp3? I used youtube-dl to rip something off youtube as a test lol, I can try messing with it to see if that's the issue, unless this is something else.

**Comment by chrisparton1991** [comment]
Hmm interesting, I would try swapping out the MP3 (or run it through a converter) and see if that helps. The other possibility is that it's related to WSL, I haven't tried running Sparkled within WSL before 🤔


Sounds like you're getting very close to seeing something light up!

**Comment by bigfoott** [comment]
Based on some quick research it appears to indeed be a WSL issue. I'll do some research and will report back with a solution for any future people that may experience the same issues :)

**Comment by chrisparton1991** [comment]
No problem, hopefully the WSL issue isn't too difficult to resolve.

Out of curiosity, is there a particular reason you want to run it inside of WSL?

**Comment by bigfoott** [comment]
Unfortunately I don't have a linux machine to run this off of. I have a handful of Discord/Twitter/etc bots build with C# running off an old Windows machine, so I figured I'd throw Sparkled on it as well in the form of WSL :)

**Comment by chrisparton1991** [comment]
You can run it directly from Windows or MacOS, you just need to install a JDK and run the jar file the same as you do in WSL :)

My Christmas display uses Sparkled on a Mac Mini. In theory you can use a Raspberry Pi as well, but I hit an issue where finding the current audio playback position took about 700 milliseconds (should be almost instantaneous). I was able to reproduce it with a minimal code snippet, so it's not a Sparkled issue. That was years ago, maybe the issue has been fixed since then.

**Comment by bigfoott** [comment]
Oh, perfect! I'll do that then. I had assumed it was linux-only but I'm now kicking myself for not trying sooner lol.  Gonna get it set up and i'll edit this reply to confirm it's good to go :)

Seriously, thank you for all the help you've been in this thread, and for making Sparkled in the first place!

**Comment by chrisparton1991** [comment]
Sweet, I'll keep my fingers crossed for you 🤞 

No problem at all, I just wish I had things in a more complete state for you!

**Comment by bigfoott** [comment]
It's fully functional! Part of my issue was the setup for static IP - not sure how I messed it up but it's working now :)

I'll be messing with this a bunch tomorrow. I also really want to see if I can help out working on the project in some way, but I'm a bit busy most of the time and want to spend some of my free time playing with Sparkled rather than working on it lol :))

Thanks again!!

**Comment by chrisparton1991** [comment]
Awesome, nice job figuring out how to get it started!

I'd love nothing more than to spend a few solid months working on Corkscore, but my current workload just won't allow it. Still, hopefully I'll have a bit of time to work on it.

If you want to help out, just raise issues with the main pain points you experience, or if you have any questions. I can't promise I'll be able to fix things in a particular timeframe, but if I know what blockers you have I can try to help you out. Feel free to show me anything cool you build!

Current priority list:
 - Finish up some database refactoring (nearly done, just not tested + pushed yet)
 - Fix up the most horrific of the UI issues (pretty sure the playlist UI is functional but basically busted, and the editors have plenty of issues)
 - Set up a GitHub action to build and push release artifacts automatically
 - Optimise the data streaming (implement some heuristic compression to reduce packet sizes, see if I can reuse buffers to reduce memory allocation)

**Comment by bigfoott** [comment]
Sounds good! I feel you on the desire to dig deep into a project but not having the time, it's super annoying :(

I'll for sure share some stuff once I get into the flow of working in the editor! There are a few QOL features I may end up attempting to add myself, we'll see lol. Specifically instant play/pause control + no auto-stopping while testing the song in the editor, and some form of BPM setting + a metronome to help sync stuff up better.
